/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
import "sst"
declare module "sst" {
  export interface Resource {
    "DBData": {
      "accountID": string
      "id": string
      "type": "sst.sst.Linkable"
    }
    "Frontend": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
    "WorkWiseJWTSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "WorkWise": cloudflare.D1Database
    "WorkWiseAPI": cloudflare.Service
    "WorkWiseUploads": cloudflare.R2Bucket
  }
}
