/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "DBData": {
      "accountID": string
      "id": string
      "type": "sst.sst.Linkable"
    }
    "Frontend": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
    "WorkWise": {
      "type": "sst.cloudflare.D1"
    }
    "WorkWiseAPI": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "WorkWiseJWTSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WorkWiseUploads": {
      "type": "sst.cloudflare.Bucket"
    }
  }
}
